const petData = [
      {
        'id': '1',
        'name': 'Buddy',
        'breed': 'Golden Retriever',
        'age': 3,
        'price': 500.0,
        'imageUrl': 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=400',
        'description': 'A friendly and energetic Golden Retriever who loves to play fetch and swim.',
        'category': 'Dog',
      },
      {
        'id': '2',
        'name': 'Luna',
        'breed': 'Persian',
        'age': 2,
        'price': 300.0,
        'imageUrl': 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400',
        'description': 'A gentle and calm Persian cat who enjoys quiet afternoons and gentle pets.',
        'category': 'Cat',
      },
      {
        'id': '3',
        'name': 'Max',
        'breed': 'German Shepherd',
        'age': 4,
        'price': 750.0,
        'imageUrl': 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=400',
        'description': 'A loyal and intelligent German Shepherd, perfect for active families.',
        'category': 'Dog',
      },
      {
        'id': '4',
        'name': 'Whiskers',
        'breed': 'British Shorthair',
        'age': 1,
        'price': 400.0,
        'imageUrl': 'https://images.unsplash.com/photo-1513245543132-31f507417b26?w=400',
        'description': 'A playful kitten with beautiful blue eyes and a curious personality.',
        'category': 'Cat',
      },
      {
        'id': '5',
        'name': 'Rocky',
        'breed': 'Bulldog',
        'age': 5,
        'price': 600.0,
        'imageUrl': 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=400',
        'description': 'A calm and gentle Bulldog who loves children and quiet environments.',
        'category': 'Dog',
      },
      {
        'id': '6',
        'name': 'Mittens',
        'breed': 'Maine Coon',
        'age': 3,
        'price': 550.0,
        'imageUrl': 'https://images.unsplash.com/photo-1574144611937-0df059b5ef3e?w=400',
        'description': 'A large and fluffy Maine Coon with a gentle giant personality.',
        'category': 'Cat',
      },
      {
        'id': '7',
        'name': 'Charlie',
        'breed': 'Beagle',
        'age': 2,
        'price': 450.0,
        'imageUrl': 'https://images.unsplash.com/photo-1551717743-49959800b1f6?w=400',
        'description': 'An energetic Beagle who loves exploring and following scents.',
        'category': 'Dog',
      },
      {
        'id': '8',
        'name': 'Shadow',
        'breed': 'Russian Blue',
        'age': 4,
        'price': 650.0,
        'imageUrl': 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=400',
        'description': 'A sophisticated Russian Blue with striking green eyes and calm demeanor.',
        'category': 'Cat',
      },
      {
        'id': '9',
        'name': 'Bella',
        'breed': 'Labrador',
        'age': 1,
        'price': 520.0,
        'imageUrl': 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=400',
        'description': 'A young and playful Labrador who loves water and fetch games.',
        'category': 'Dog',
      },
      {
        'id': '10',
        'name': 'Smokey',
        'breed': 'Siamese',
        'age': 6,
        'price': 380.0,
        'imageUrl': 'https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=400',
        'description': 'A talkative and affectionate Siamese cat who loves attention.',
        'category': 'Cat',
      },
      {
        'id': '11',
        'name': 'Duke',
        'breed': 'Rottweiler',
        'age': 3,
        'price': 700.0,
        'imageUrl': 'https://images.unsplash.com/photo-1605568427561-40dd23c2acea?w=400',
        'description': 'A strong and loyal Rottweiler, excellent guard dog and family companion.',
        'category': 'Dog',
      },
      {
        'id': '12',
        'name': 'Princess',
        'breed': 'Ragdoll',
        'age': 2,
        'price': 480.0,
        'imageUrl': 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=400',
        'description': 'A docile and calm Ragdoll cat who loves being held and cuddled.',
        'category': 'Cat',
      }
];

module.exports = petData;
